import { useState, useRef } from 'react'
import { ShieldAlert, Activity, Upload, Download, FileJson } from 'lucide-react'
import './index.css'

function App() {
  const [report, setReport] = useState<any>(null)
  const [selectedLog, setSelectedLog] = useState<any>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return

    const MAX_SIZE_MB = 50
    if (file.size > MAX_SIZE_MB * 1024 * 1024) {
      alert(`File too large (${(file.size / 1024 / 1024).toFixed(1)} MB). Maximum is ${MAX_SIZE_MB} MB. Tip: re-run test_harness.py with fewer raw logs.`)
      return
    }

    const reader = new FileReader()
    reader.onload = (evt) => {
      try {
        const json = JSON.parse(evt.target?.result as string)
        setReport(json)
      } catch (err) {
        alert("Failed to parse JSON report. Ensure it is the validation_report.json generated by test_harness.py")
      }
    }
    reader.readAsText(file)
  }

  const exportCSV = () => {
    if (!report) return
    const headers = "Source IP,Classification,Start Time,End Time,Event Count\n"
    const rows = report.alerts.map((a: any) => 
      `${a.source_ip},${a.classification},${a.window_start},${a.window_end},${a.event_count}`
    ).join("\n")
    
    const blob = new Blob([headers + rows], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `validation_export_${Date.now()}.csv`
    a.click()
  }

  // Calculate metrics dynamically
  const tpCount = report?.alerts.filter((a: any) => a.classification === 'TRUE POSITIVE').length || 0
  const fpCount = report?.alerts.filter((a: any) => a.classification === 'FALSE POSITIVE').length || 0

  return (
    <div className="dashboard-container">
      
      {/* Modal for Raw Logs */}
      {selectedLog && (
        <div style={{ position: 'fixed', top: 0, left: 0, width: '100%', height: '100%', backgroundColor: 'rgba(11, 14, 20, 0.9)', zIndex: 9999, display: 'flex', justifyContent: 'center', alignItems: 'center' }} onClick={() => setSelectedLog(null)}>
          <div style={{ background: 'var(--surface)', padding: '2rem', border: '1px solid var(--hairline)', borderRadius: '8px', maxWidth: '900px', width: '90%', maxHeight: '80vh', display: 'flex', flexDirection: 'column' }} onClick={e => e.stopPropagation()}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '1rem', borderBottom: '1px solid var(--hairline)', paddingBottom: '1rem' }}>
              <h3 style={{ fontFamily: 'ui-monospace, monospace' }}>Raw Log Inspection</h3>
              <button onClick={() => setSelectedLog(null)} style={{ color: 'var(--text-muted)', background: 'none', border: 'none', cursor: 'pointer' }}>[ Close Modal ]</button>
            </div>
            <div style={{ overflowY: 'auto', flexGrow: 1 }}>
              <pre className="data-text" style={{ color: 'var(--text-muted)', whiteSpace: 'pre-wrap', wordBreak: 'break-all' }}>
                {JSON.stringify(selectedLog, null, 2)}
              </pre>
            </div>
          </div>
        </div>
      )}

      {/* Header */}
      <header className="header flex-between" style={{ paddingBottom: '1.5rem', borderBottom: '1px solid var(--hairline)', marginBottom: '1.5rem' }}>
        <div>
          <h1>Adversary Emulation Lab</h1>
          <p className="text-muted">Detection Validation Harness & Telemetry Viewer</p>
        </div>
        <div className="flex-center gap-sm">
          <input 
            type="file" 
            accept=".json" 
            style={{ display: 'none' }} 
            ref={fileInputRef}
            onChange={handleFileUpload}
          />
          <button 
            onClick={() => fileInputRef.current?.click()}
            style={{ padding: '8px 16px', background: 'transparent', border: '1px dashed var(--signal)', color: 'var(--signal)', display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer', borderRadius: '4px' }}
          >
            <Upload size={16} /> Load validation_report.json
          </button>
          <button 
            onClick={exportCSV}
            disabled={!report}
            style={{ padding: '8px 16px', background: 'transparent', border: '1px solid var(--hairline)', color: report ? 'var(--text-primary)' : 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '8px', cursor: report ? 'pointer' : 'not-allowed', borderRadius: '4px' }}
          >
            <Download size={16} /> Export CSV
          </button>
        </div>
      </header>

      {/* Top Stats */}
      <div className="stats-grid">
        <div className="stat-card">
          <div className="stat-label">Active Sensors</div>
          <div className={`stat-value flex-center ${report ? 'text-primary' : 'text-muted'}`}>
            <Activity size={24} color={report ? "var(--ok)" : "var(--text-muted)"} /> {report ? 1 : '-'}
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Rules Evaluated</div>
          <div className={`stat-value ${report ? 'text-primary' : 'text-muted'}`}>
            {report ? 1 : '-'}
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-label">True Positives</div>
          <div className={`stat-value ${tpCount > 0 ? 'text-critical' : 'text-muted'}`}>
            {report ? tpCount : '-'}
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-label">False Positives</div>
          <div className={`stat-value ${fpCount > 0 ? 'text-warn' : (report ? 'text-ok' : 'text-muted')}`}>
            {report ? fpCount : '-'}
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="content-grid">
        
        {/* Left Panel: Recent Alerts */}
        <div className="panel" style={{ overflow: 'hidden' }}>
          <div className="panel-title flex-between">
            <span className="flex-center gap-sm"><ShieldAlert size={16} /> Validated Alerts</span>
            <span className="data-text">{report ? report.timestamp.replace('T', ' ').substring(0, 19) + ' UTC' : 'Awaiting data'}</span>
          </div>
          
          {!report ? (
             <div className="empty-state">
               [ No telemetry ingested. Please click "Load validation_report.json" ]
             </div>
          ) : report.alerts.length === 0 ? (
             <div className="empty-state" style={{ border: 'none' }}>
               [ Validation complete. No alerts generated for this dataset. ]
             </div>
          ) : (
            <div style={{ overflowX: 'auto' }}>
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Class</th>
                    <th>Source IP</th>
                    <th>Start Window (UTC)</th>
                    <th>Event Count</th>
                    <th>Raw</th>
                  </tr>
                </thead>
                <tbody>
                  {report.alerts.map((a: any, i: number) => (
                    <tr key={i}>
                      <td>
                        <span className={`badge ${a.classification === 'TRUE POSITIVE' ? 'critical' : a.classification === 'FALSE POSITIVE' ? 'warn' : 'ok'}`}>
                          {a.classification}
                        </span>
                      </td>
                      <td className="data-text" style={{ whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', maxWidth: '150px' }} title={a.source_ip}>{a.source_ip}</td>
                      <td className="data-text" style={{ whiteSpace: 'nowrap' }}>{a.window_start.replace('T', ' ').substring(0, 19)}</td>
                      <td className="data-text">{a.event_count}</td>
                      <td>
                        <button onClick={() => setSelectedLog(a.raw_logs)} title="View Raw Zeek Logs" style={{ cursor: 'pointer', background: 'none', border: 'none' }}>
                          <FileJson size={16} color="var(--signal)" />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* Right Panel: Rule Efficacy */}
        <div className="panel">
          <div className="panel-title">Rule Efficacy Summary</div>
          
          {!report ? (
            <div className="empty-state">
              [ Awaiting validation results ]
            </div>
          ) : (
            <div style={{ borderBottom: '1px solid var(--hairline)', paddingBottom: '1rem' }}>
              <div style={{ fontSize: '0.875rem', margin: '0.5rem 0' }}>{report.rule_name}</div>
              <div className="flex-between" style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                <span>Threshold: &gt;={report.threshold}</span>
                <span className={fpCount > 0 ? 'text-warn' : 'text-ok'}>
                  {tpCount} TP / {fpCount} FP
                </span>
              </div>
            </div>
          )}
        </div>

      </div>

    </div>
  )
}

export default App
